### ISSUE TITLE
Missing MySQL PDO Driver in Php

### ISSUE THREAD

**Issue by rsmereka** [NuTyX/packages-i686#1]
In your next compile of Php for i386, can you please include the MySQL PDO driver or offer the shared library via some other package. To compile this driver in Php, you will want to use the:
`--with-pdo-mysql`
switch as described in:
[http://anduin.linuxfromscratch.org/BLFS/files/php_configure.txt](url)

Thank you,
Rick Smereka

**Comment by tnut** [comment]
Thank a lot for your interest in NuTyX.
Will implement this days (today or tomorrow)

**Comment by tnut** [comment]
Done
